version: 1
lr_schedulers:
  # Learning rate decay scheduler
  training_lr:
    class: StepLR
    gamma: 0.2
    step_size: 60

# # attempt at regularizing different layers differently
# regularizers:
#   Channels_groups_regularizer:
#     class: L1Regularizer
#     reg_regims:
#       module.module._conv_stem.weight: 1e-05
#       module.module._blocks.0._depthwise_conv.weight: 0.0
#       module.module._blocks.0._se_reduce.weight: 1e-05
#       module.module._blocks.0._se_expand.weight: 1e-05
#       module.module._blocks.0._project_conv.weight: 1e-05
#       module.module._blocks.1._expand_conv.weight: 1e-05
#       module.module._blocks.1._depthwise_conv.weight: 0.0
#       module.module._blocks.1._se_reduce.weight: 1e-05
#       module.module._blocks.1._se_expand.weight: 1e-05
#       module.module._blocks.1._project_conv.weight: 1e-05
#       module.module._blocks.2._expand_conv.weight: 1e-05
#       module.module._blocks.2._depthwise_conv.weight: 0.0
#       module.module._blocks.2._se_reduce.weight: 1e-05
#       module.module._blocks.2._se_expand.weight: 1e-05
#       module.module._blocks.2._project_conv.weight: 1e-05
#       module.module._blocks.3._expand_conv.weight: 1e-05
#       module.module._blocks.3._depthwise_conv.weight: 0.0
#       module.module._blocks.3._se_reduce.weight: 1e-05
#       module.module._blocks.3._se_expand.weight: 1e-05
#       module.module._blocks.3._project_conv.weight: 1e-05
#       module.module._blocks.4._expand_conv.weight: 1e-05
#       module.module._blocks.4._depthwise_conv.weight: 0.0
#       module.module._blocks.4._se_reduce.weight: 1e-05
#       module.module._blocks.4._se_expand.weight: 1e-05
#       module.module._blocks.4._project_conv.weight: 1e-05
#       module.module._blocks.5._expand_conv.weight: 1e-05
#       module.module._blocks.5._depthwise_conv.weight: 0.0
#       module.module._blocks.5._se_reduce.weight: 1e-05
#       module.module._blocks.5._se_expand.weight: 1e-05
#       module.module._blocks.5._project_conv.weight: 1e-05
#       module.module._blocks.6._expand_conv.weight: 1e-05
#       module.module._blocks.6._depthwise_conv.weight: 0.0
#       module.module._blocks.6._se_reduce.weight: 1e-05
#       module.module._blocks.6._se_expand.weight: 1e-05
#       module.module._blocks.6._project_conv.weight: 1e-05
#       module.module._blocks.7._expand_conv.weight: 1e-05
#       module.module._blocks.7._depthwise_conv.weight: 0.0
#       module.module._blocks.7._se_reduce.weight: 1e-05
#       module.module._blocks.7._se_expand.weight: 1e-05
#       module.module._blocks.7._project_conv.weight: 1e-05
#       module.module._blocks.8._expand_conv.weight: 1e-05
#       module.module._blocks.8._depthwise_conv.weight: 0.0
#       module.module._blocks.8._se_reduce.weight: 1e-05
#       module.module._blocks.8._se_expand.weight: 1e-05
#       module.module._blocks.8._project_conv.weight: 1e-05
#       module.module._blocks.9._expand_conv.weight: 1e-05
#       module.module._blocks.9._depthwise_conv.weight: 0.0
#       module.module._blocks.9._se_reduce.weight: 1e-05
#       module.module._blocks.9._se_expand.weight: 1e-05
#       module.module._blocks.9._project_conv.weight: 1e-05
#       module.module._blocks.10._expand_conv.weight: 1e-05
#       module.module._blocks.10._depthwise_conv.weight: 0.0
#       module.module._blocks.10._se_reduce.weight: 1e-05
#       module.module._blocks.10._se_expand.weight: 1e-05
#       module.module._blocks.10._project_conv.weight: 1e-05
#       module.module._blocks.11._expand_conv.weight: 1e-05
#       module.module._blocks.11._depthwise_conv.weight: 0.0
#       module.module._blocks.11._se_reduce.weight: 1e-05
#       module.module._blocks.11._se_expand.weight: 1e-05
#       module.module._blocks.11._project_conv.weight: 1e-05
#       module.module._blocks.12._expand_conv.weight: 1e-05
#       module.module._blocks.12._depthwise_conv.weight: 0.0
#       module.module._blocks.12._se_reduce.weight: 1e-05
#       module.module._blocks.12._se_expand.weight: 1e-05
#       module.module._blocks.12._project_conv.weight: 1e-05
#       module.module._blocks.13._expand_conv.weight: 1e-05
#       module.module._blocks.13._depthwise_conv.weight: 0.0
#       module.module._blocks.13._se_reduce.weight: 1e-05
#       module.module._blocks.13._se_expand.weight: 1e-05
#       module.module._blocks.13._project_conv.weight: 1e-05
#       module.module._blocks.14._expand_conv.weight: 1e-05
#       module.module._blocks.14._depthwise_conv.weight: 0.0
#       module.module._blocks.14._se_reduce.weight: 1e-05
#       module.module._blocks.14._se_expand.weight: 1e-05
#       module.module._blocks.14._project_conv.weight: 1e-05
#       module.module._blocks.15._expand_conv.weight: 1e-05
#       module.module._blocks.15._depthwise_conv.weight: 0.0
#       module.module._blocks.15._se_reduce.weight: 1e-05
#       module.module._blocks.15._se_expand.weight: 1e-05
#       module.module._blocks.15._project_conv.weight: 1e-05
#       module.module._conv_head.weight: 1e-05
#       module.module._fc.weight: 1e-05

policies:
  - lr_scheduler:
      instance_name: training_lr
    starting_epoch: 0
    ending_epoch: 180
    frequency: 1
